In [2]:
import numpy as np
import pandas as pd

# Exercício 1

O banco de dados possui informações sobre a distribuição de respiradores para tratamento da Covid-19 no Brasil. Com base neste dataset, faça:

Leia o dataset com a função pd.read_csv() e armazene em uma variável df;

* Imprima as 10 primeiras linhas;

* Imprima as 3 últimas linhas;

* Imprima as colunas do dataset;

* Mostre informações sobre o objeto df;

* Mostre o tipo de dado de cada coluna;

* Mostre o número de linhas do objeto df;

* Mostre a quantidade de missing em cada coluna do DataFrame.

Baixe o dataset anexo nesta aula, para resolver este exercício.

Recursos para esta aula

pd.read_csv('../Dados/distribuicao_respiradores_BR.csv')

In [3]:
pd.read_csv('../Dados/distribuicao_respiradores_BR.csv')

DATA;FORNECEDOR;DESTINO;ESTADO/MUNICIPIO;TIPO;QUANTIDADE;VALOR;DESTINATARIO;UF
0     19/04/2020;VYAIRE;RIO DE JANEIRO;ESTADO;UTI;40...                            
1     22/04/2020;VYAIRE;RIO DE JANEIRO;ESTADO;UTI;20...                            
2     08/05/2020;MAGNAMED;RIO DE JANEIRO;ESTADO;UTI;...                            
3     08/05/2020;KTK;RIO DE JANEIRO;ESTADO;UTI;15;90...                            
4     09/05/2020;LEISTUNG;RIO DE JANEIRO;ESTADO;UTI;...                            
...                                                 ...                            
1600  21/09/2020;LEISTUNG;PARANA;MUNICIPIO;UTI;5;300...                            
1601  21/09/2020;LEISTUNG;PARANA;MUNICIPIO;UTI;1;600...                            
1602  24/09/2020;KTK;PARANA;MUNICIPIO;UTI;2;120000;S...                            
1603  24/09/2020;VYAIRE LTV 2200 USA;PARANA;MUNICIPI...                            
1604  07/08/2020;MAGNAMED;LIBANO;-;TRANSPORTE;300;14...                            

[1605 rows x 1 columns]

# Exercício 2

Ainda com o dataset anterior siga os passos abaixo:

* Converta a coluna DATA para datetime;

* Converta a coluna VALOR para float;

* Mostre os valores únicos da coluna FORNECEDOR;

* Mostre os valores únicos da coluna TIPO;

* Mostre a quantidade de destinatários únicos.

In [18]:
def inspecionar_array(array):
   if isinstance(array, np.ndarray):
    print(f'Shape: {array.shape}')
    print(f'Size: {array.size}')
    print(f'Ndim: {array.ndim}')
    print(f'Nbytes: {array.nbytes}')
    print(f'Dtype: {array.dtype}')
    print(f'Type: {type(array)}')
    print(array)
   else:
      return 'O objeto inserido não é um array NumPy.'

inspecionar_array(np.array([1,2,3,4]))
inspecionar_array([1,2,3])



Shape: (4,)
Size: 4
Ndim: 1
Nbytes: 32
Dtype: int64
Type: <class 'numpy.ndarray'>
[1 2 3 4]


'O objeto inserido não é um array NumPy.'

# Exercício 3

Após as operações efetuadas nos exercícios 1 e 2, salve o banco de dados no formato CSV com o nome 'distribuicao_respiradores-modificado.csv'. Use ';' como separador.

In [39]:
a = np.array([-1, 4, 7, 9])
b = np.array(range(1,11))
tupla = (10,11,12,13,14)
c = np.array(tupla)
d = np.array(range(1990,2021,5))
e = np.array(range(2020,1899,-10))
f = np.array(100)

print(a)
print()
print(b)
print()
print(c)
print()
print(d)
print()
print(e)
print()
print(f)

[-1  4  7  9]

[ 1  2  3  4  5  6  7  8  9 10]

[10 11 12 13 14]

[1990 1995 2000 2005 2010 2015 2020]

[2020 2010 2000 1990 1980 1970 1960 1950 1940 1930 1920 1910 1900]

100


# Exercício 4

Após as operações efetuadas nos exercícios 1 e 2, converta o banco de dados para o formato Excel.

In [40]:
a = np.ones(shape= 10)
b = np.ones(shape= (4,4))
c = np.ones(shape= (2,3), dtype= int)

print(a)
print()
print(b)
print()
print(c)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1 1 1]
 [1 1 1]]


# Exercício 5

Carregue o banco de dados CardioGoodFitness anexo nesta aula;

* Imprima o número de linhas e colunas do dataset;

* Imprima as 3 primeiras linhas do DataFrame;

* Imprima as 2 últimas linhas do DataFrame;

* Imprima o tipo de dado de cada coluna;

* Converta a coluna Income para float;

* Imprima os valores únicos da coluna Product;

* Imprima os valores únicos da coluna MaritalStatus;

* Imprima a proporção de homens e mulheres.

Recursos para esta aula

pd.read_csv('../Dados/CardioGoodFitness.csv')


In [43]:
a = np.zeros(shape= 10)
b = np.zeros(shape= (2,2))
c = np.zeros(shape= (4,6))

print(a)
print()
print(b)
print()
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0.]
 [0. 0.]]

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# Exercício 6

Após as operaões realizadas no exercício 5, converta o banco de dados para o formato Json.

In [57]:
a = np.arange(start= 10, stop= 50, step= 5).reshape((-1, 1))
b = np.arange(start= -50, stop= -4, step= 5)
c = np.arange(start= 50, stop= 150, step= 2).reshape((-1,10))

print(a)
print()
print(b)
print()
print(c)

[[10]
 [15]
 [20]
 [25]
 [30]
 [35]
 [40]
 [45]]

[-50 -45 -40 -35 -30 -25 -20 -15 -10  -5]

[[ 50  52  54  56  58  60  62  64  66  68]
 [ 70  72  74  76  78  80  82  84  86  88]
 [ 90  92  94  96  98 100 102 104 106 108]
 [110 112 114 116 118 120 122 124 126 128]
 [130 132 134 136 138 140 142 144 146 148]]


# Exercício 7

Use a função pd.read_html() para obter os principais indicadores econômicos dos EUA entre 1980-2020 (estimativa). Use como referência o link: https://en.wikipedia.org/wiki/Economy_of_the_United_States.

In [64]:
a = np.full(shape= 10, fill_value= 5, dtype= float)
b = np.full(shape= (4,4), fill_value= -5, dtype= float)
c = np.full(shape= (3,3), fill_value= 3, dtype= int)
d = np.full(shape= (10,10), fill_value= 50)

print(a)
print()
print(b)
print()
print(c)
print()
print(d)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

[[-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]]

[[3 3 3]
 [3 3 3]
 [3 3 3]]

[[50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]]


# Exercício 8

Salve a tabela anterior no formato CSV.

# Exercício 9

Baixe o dataset anexo nesta aula, que foi gerado a partir da base FAOSTAT e refere-se a dados de produção e produtividade de commodities selecionadas para alguns países, entre 2016-2018. Siga os passos abaixo:

* Leia o dataset e armazene em uma variável;

* Imprima o shape do dataset;

* Imprima informações do dataset;

* Imprima o tipo de dado de cada coluna;

* Remova as colunas: 'Domain Code', 'Domain', 'Area Code', 'Element Code', 'Item Code', 'Year Code', 'Flag', 'Flag Description';

* Converta o dtype da coluna Value para float.

Recursos para esta aula

pd.read_csv('../Dados/FAOSTAT_data_12-5-2020.csv')

In [4]:
pd.read_csv('../Dados/FAOSTAT_data_12-5-2020.csv')

Domain Code Domain  Area Code                      Area  Element Code  \
0           QC  Crops          9                 Argentina          5419   
1           QC  Crops          9                 Argentina          5419   
2           QC  Crops          9                 Argentina          5419   
3           QC  Crops          9                 Argentina          5510   
4           QC  Crops          9                 Argentina          5510   
..         ...    ...        ...                       ...           ...   
61          QC  Crops        231  United States of America          5419   
62          QC  Crops        231  United States of America          5419   
63          QC  Crops        231  United States of America          5510   
64          QC  Crops        231  United States of America          5510   
65          QC  Crops        231  United States of America          5510   

       Element  Item Code      Item  Year Code  Year    Unit     Value Flag  \
0        Yield        515    Apples       2016  2016   hg/ha    223912   Fc   
1        Yield        515    Apples       2017  2017   hg/ha    235386   Fc   
2        Yield        515    Apples       2018  2018   hg/ha    213072   Fc   
3   Production        515    Apples       2016  2016  tonnes    458908  NaN   
4   Production        515    Apples       2017  2017  tonnes    458908  NaN   
..         ...        ...       ...        ...   ...     ...       ...  ...   
61       Yield        388  Tomatoes       2017  2017   hg/ha    886625   Fc   
62       Yield        388  Tomatoes       2018  2018   hg/ha    968079   Fc   
63  Production        388  Tomatoes       2016  2016  tonnes  12877049  NaN   
64  Production        388  Tomatoes       2017  2017  tonnes  11141862  NaN   
65  Production        388  Tomatoes       2018  2018  tonnes  12612139  NaN   

   Flag Description  
0   Calculated data  
1   Calculated data  
2   Calculated data  
3     Official data  
4     Official data  
..              ...  
61  Calculated data  
62  Calculated data  
63    Official data  
64    Official data  
65    Official data  

[66 rows x 14 columns]

# Exercício 10

Após as operações realizadas no exercício 9, salve o dataset no formato CSV.

In [74]:
np.linspace(start=1, stop=21, num= 5)

array([ 1.,  6., 11., 16., 21.])