In [1]:
import numpy as np
import pandas as pd

# Exercícios 1-5

**1**

* Instale e use o Seaborn para gerar as visualizações desta seção (pip install seaborn);

* Carregue o dataset Iris anexo nesta aula;

* Remova a coluna Id;

* Use a função countplot() para mostrar a frequência das três espécies de Iris do dataset.

**2**

* Faça um scatter plot para mostrar a relação entre 'SepalLengthCm' e 'SepalWidthCm';

* Faça um scatter plot para mostrar a relação entre 'PetalLengthCm' e 'PetalWidthCm'.

**3**

* Faça um histograma das features do dataset (exclusive coluna Species).

**4**

* Faça um boxplot das features do dataset (exclusive coluna Species).

**5**

* Faça um heatmap das features do dataset (exclusive coluna Species);

* Faça um pairplot para analisar a correlação entre as variáveis do dataset.

Recursos para esta aula

pd.read_csv('../Dados/Iris.csv')

In [7]:
array = np.array([10, 5, 3, 200])
print(array.shape)
print(array.size)
print(array.ndim)
print(array.nbytes)
print(array.dtype)
print(type(array))

(4,)
4
1
32
int64
<class 'numpy.ndarray'>


# Exercícios 6-15

**6**

* Use o código abaixo para carregar o dataset tips com o Seaborn (que apresenta dados acerca da gorjeta paga por clientes, e ovalor total da conta , bem como outras informações);

```
import seaborn as sns
tips = sns.load_dataset('tips')
```

* Apresente as estatísticas descritivas do dataset com a função describe();

* Mostre as colunas do dataset;

* Mostre o shape do dataset;

* Verifique os valores únicos das colunas sex, smoker, day e time;

* Apresente a proporção entre homens e mulheres;

* Apresente a proporção entre fumantes e não fumantes;

**7**

* Use a função sns.countplot() para construir um gráfico com os dados categóricos do dataset.

**8**

* Use a função sns.scatterplot() para visualizar a relação entre as variáveis 'total_bill' e 'tip';

* Utilize a função sns.scatterplot() para visualizar a relação entre as variáveis 'total_bill' e 'tip' e use o argumento hue para colorir cada ponto com a variável 'sex'.

**9**

* Utilize a função sns.relplot() para visualizar a relação entre as variáveis 'tip' e 'size' e use ainda o argumento hue para colorir cada ponto com a variável 'smoker'.

**10**

* Construa um boxplot para as variáveis quantitativas do dataset.

**11**

* Use a função sns.histplot() para visualizar a distribuição das variáveis 'tip' e 'total_bill'.

**12**

* Construa um heatmap para o visualizar o grau de relação entre as variáveis.

**13**

* Faça um pairplot para analisar a relação entre as variáveis do dataset.

**14**

* Use a função sns.lmplot() para visualizar a relação entre 'total_bill' e 'tip', ajustando um reta de regressão linear.

**15**

* Use a função sns.lmplot() para visualizar a relação entre 'total_bill' e 'tip', ajustando um reta de regressão linear e use ainda o argumento hue para colorir cada ponto com a variável 'smoker'.

In [18]:
def inspecionar_array(array):
   if isinstance(array, np.ndarray):
    print(f'Shape: {array.shape}')
    print(f'Size: {array.size}')
    print(f'Ndim: {array.ndim}')
    print(f'Nbytes: {array.nbytes}')
    print(f'Dtype: {array.dtype}')
    print(f'Type: {type(array)}')
    print(array)
   else:
      return 'O objeto inserido não é um array NumPy.'

inspecionar_array(np.array([1,2,3,4]))
inspecionar_array([1,2,3])



Shape: (4,)
Size: 4
Ndim: 1
Nbytes: 32
Dtype: int64
Type: <class 'numpy.ndarray'>
[1 2 3 4]


'O objeto inserido não é um array NumPy.'

# Exercícios 16-20

Com base no DataFrame abaixo responda:

```
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
 
np.random.seed(20)
n = 2_000  #size
data = {
    'A': np.random.normal(loc = 100, scale = 1, size = n),
    'B': np.random.normal(loc = 100, scale = 2, size = n),
    'C': np.random.normal(loc = 100, scale = 5, size = n),
    'D': np.random.lognormal(mean = 2, sigma = 1.1, size = n),
    'E': np.random.lognormal(mean = 2, sigma = 1.2, size = n),
    'F': np.random.lognormal(mean = 2, sigma = 1.3, size = n),
    'G': np.random.randn(n),
    'H': np.random.binomial(n = 10, p = 0.8, size = n)
}
 
df = pd.DataFrame(data)
```

**16**

* Use a função sns.kdeplot() para demonstrar em um único plot a distribuição das variáveis 'A', 'B' e 'C', que seguem uma distribuição normal.

**17**

* Use a função sns.kdeplot() para demonstrar em um único plot a distribuição das variáveis 'D', 'E' e 'F', que seguem uma distribuição lognormal.

**18**

* Use a função sns.joinplot() para demonstrar a relação entra variáveis 'A' e 'B',evidenciando suas respectivas distribuições. Repita o mesmo procedimento para as variáveis 'D' e 'F'.

**19**

* Elabore um histograma individual para as variáveis do dataset.

**20**

* Elabore um violinplot para as variáveis 'G' e 'H', respectivamente. Este gráfico consiste em uma combinação do boxplot com o kernel density estimate (kde).

In [39]:
a = np.array([-1, 4, 7, 9])
b = np.array(range(1,11))
tupla = (10,11,12,13,14)
c = np.array(tupla)
d = np.array(range(1990,2021,5))
e = np.array(range(2020,1899,-10))
f = np.array(100)

print(a)
print()
print(b)
print()
print(c)
print()
print(d)
print()
print(e)
print()
print(f)

[-1  4  7  9]

[ 1  2  3  4  5  6  7  8  9 10]

[10 11 12 13 14]

[1990 1995 2000 2005 2010 2015 2020]

[2020 2010 2000 1990 1980 1970 1960 1950 1940 1930 1920 1910 1900]

100


# Exercícios 21-25

Carregue o dataset anexo nesta aula e em seguida faça:

```
import pandas as pd
series = pd.read_csv( 'Airline_passengers.csv' , header=0, index_col=0, parse_dates=True,
squeeze=True)
```

**21**

Apresente as estatísticas descritivas da série temporal com a função describe();

Mostre o shape do dataset.

**22**

Faça um gráfico de linhas para demonstrar a evolução da variável 'Airline-passengers' no tempo.

**23**

Faça um boxplot caracterizar a variável 'Airline-passengers'.

**24**

Faça um histograma e um kde plot.

**25**

Importe a função lag_plot e aplique a série temporal (esta função gera um lag plot para séries temporais.)

```
from pandas.plotting import lag_plot
```

Recursos para esta aula

pd.read_csv('../Dados/Airline_passengers.csv')

In [40]:
a = np.ones(shape= 10)
b = np.ones(shape= (4,4))
c = np.ones(shape= (2,3), dtype= int)

print(a)
print()
print(b)
print()
print(c)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1 1 1]
 [1 1 1]]
