In [1]:
import numpy as np
import pandas as pd

# Exercícios 1-14
1. Importe o banco de dados anexo nesta aula, que diz respeito a dados de produção e produtividade para commodities selecionadas entre 2016-2018;

2. Mostre as 3 primeiras linhas e posteriormente as 2 últimas linhas;

3. Imprima as colunas e o índice do DataFrame;

4. Imprima o shape do DataFrame;

5. Mostre o tipo de dado em cada coluna;

6. Mostre informações do dataset;

7. Mostre os valores únicos nas colunas Area, Element e Item;

8. Remova as colunas: 'Domain Code', 'Domain', 'Area Code', 'Element Code', 'Item Code', 'Year Code', 'Flag', 'Flag Description';

9. Crie e aplique uma função na coluna Area que converta o nome de cada país em suas respectivas siglas;

10. Converta o dtype da coluna Value para float;

11. Crie uma nova coluna denominada Country/Commodity, que corresponde a concatenação das colunas Area e Item;

12. Agrupe os dados em produção e produtividade (coluna Element) e armazene em variáveis distintas;

13. Mude o shape dos dataframes criados no exercício anterior, com a função pivot, de modo que os novos objetos tenham índice  'Year', coluna 'Country/Commodity' e os valores correspondam a coluna 'Value';

14. Concatene os objetos criados no exercício anterior, ao longo do eixo 0, com a função pd.concat(), passe como keys a lista ['Production', 'Yield'].

Recursos para esta aula

pd.read_csv('../Dados/FAOSTAT_data_12-5-2020.csv')

In [7]:
array = np.array([10, 5, 3, 200])
print(array.shape)
print(array.size)
print(array.ndim)
print(array.nbytes)
print(array.dtype)
print(type(array))

(4,)
4
1
32
int64
<class 'numpy.ndarray'>


# Exercícios 15-32

15. Importe o banco de dados anexo nesta aula;

16. Mostre as 5 primeiras linhas;

17. Mostre as colunas e o índice do dataset;

18. Mostre o shape do dataset;

19. Mostre informações do objeto criado com a função info();

20. Mostre o dtype de cada coluna;

21. Remova as seguintes colunas: 'id', 'date', 'zipcode', 'lat', 'long';

22. Verifique se há missing data no dataset;

23. Mostre estatísticas descritivas do dataset com a função describe();

24. Calcule a matriz de correlação;

25. Calcule a matriz de covariância;

26. Faça um mapa de calor com base na matriz de correlação, use o módulo Seaborn;

27. Faça um gráfico das relações entre as variáveis do dataset com a função pairplot do módulo Seaborn;

28. Defina a variável target (coluna 'price') e armazene em uma variável;

29. Defina as variáveis preditoras, que serão utilizadas para explicar o preço, e armazene em uma variável;

30. Use a função train_test_split do sklearn para separar o dataset em dados de treino e teste, defina o test_size = 0.3 e random_state = 33;

31. Crie um modelo de regressão linear e ajuste aos dados de treino, use: from sklearn.linear_model import LinearRegression;

32. Calcule o coeficiente de determinação do modelo com a função score(), passando os dados de teste;

Recursos para esta aula

pd.read_csv('../Dados/kc_house_data.csv')

In [18]:
def inspecionar_array(array):
   if isinstance(array, np.ndarray):
    print(f'Shape: {array.shape}')
    print(f'Size: {array.size}')
    print(f'Ndim: {array.ndim}')
    print(f'Nbytes: {array.nbytes}')
    print(f'Dtype: {array.dtype}')
    print(f'Type: {type(array)}')
    print(array)
   else:
      return 'O objeto inserido não é um array NumPy.'

inspecionar_array(np.array([1,2,3,4]))
inspecionar_array([1,2,3])



Shape: (4,)
Size: 4
Ndim: 1
Nbytes: 32
Dtype: int64
Type: <class 'numpy.ndarray'>
[1 2 3 4]


'O objeto inserido não é um array NumPy.'

# Exercícios 33-55

33. Importe o banco de dados anexo nesta aula, que apresenta dados sobre a performance de estudantes nas provas de matemática, redação e escrita;

34. Mostre as 10 primeiras linhas; e ainda as 3 últimas;

35. Mostre informações do dataset com a função info();

36. Mostre as colunas e o índice do dataset;

37. Mostre o shape do dataset;

38. Mostre o dtype de cada coluna;

39. Modifique o nome das colunas do dataset, substitua ' ' por '_', use ainda a função title();

40. Crie um laço de repetição e mostre a distribuição dos dados em cada coluna com a função value_counts(); ordene os valores exibidos;

41. Armazene o nome das provas em uma lista (Math_Score, Reading_Score e Writing_Score);

42. Calcule o percentual (%) de missings nas colunas do dataset;

43. Mostre estatísticas descritivas do dataset com a função describe();

44. Agrupe os dados por gênero e posteriormente mostre as estatísticas descritvas para as provas (média, mediana, variância e desvio padrão);

45. Considerando as variáveis Gênero e se os alunos fizeram curso Preparatório, refaça o exercício anterior;

46. Agrupe os dados por Raça/Etnia e Grau de Escolaridade dos Pais e calcule a média das provas para estes grupos;

47. Gere um gráfico para a proporção entre os gêneros;

48. Gere um gráfico de barras para mostrar a distribuição da coluna Raça/Etnia;

49. Gere um gráfico de barras para mostrar a distribuição do nível de escolaridade dos pais por gênero;

50. Gere um gráfico de barras para mostrar a distribuição do Almoço (coluna Lunch) por gênero;

51. Gere um boxplot para mostrar a distribuição das notas;

52. Gere um gráfico com subplots com 3 colunas, em que cada plot demonstra a distribuição da nota das provas de acordo com a realização ou não do curso preparatório;

53. Calcule a matriz de correlação e a matriz de covariância;

54. Gere um mapa de calor para analisar a relação entre as features do dataset;

55. Use o Seaborn para gerar um pairplot das notas por gênero.

Recursos para esta aula

pd.read_csv('../Dados/kc_house_data.csv')

In [39]:
a = np.array([-1, 4, 7, 9])
b = np.array(range(1,11))
tupla = (10,11,12,13,14)
c = np.array(tupla)
d = np.array(range(1990,2021,5))
e = np.array(range(2020,1899,-10))
f = np.array(100)

print(a)
print()
print(b)
print()
print(c)
print()
print(d)
print()
print(e)
print()
print(f)

[-1  4  7  9]

[ 1  2  3  4  5  6  7  8  9 10]

[10 11 12 13 14]

[1990 1995 2000 2005 2010 2015 2020]

[2020 2010 2000 1990 1980 1970 1960 1950 1940 1930 1920 1910 1900]

100


# Exercícios 56-33

56. Importe o banco de dados anexo nesta aula, que apresenta dados sobre salário em termos dos anos de experiência para cada indivíduo;

57. Mostre as 5 primeiras linhas;

58. Mostre as colunas e o índice do dataset;

59. Mostre o shape do dataset e a quantidade de observações;

60. Mostre informações do objeto criado com a função info();

61. Mostre o dtype de cada coluna;

62. Verifique se há missing data no dataset;

63. Mostre estatísticas descritivas do dataset com a função describe();

64. Calcule a matriz de correlação;

65. Calcule a matriz de covariância;

66. Faça um mapa de calor com base na matriz de correlação, use o módulo Seaborn;

67. Faça um gráfico scatter plot entre as variáveis Salário e Anos de Experiência;

68. Gere um boxplot para cada variável do dataset;

69. Defina a variável target (salário) e armazene em uma variável;

70. Defina variável preditora, que será utilizada para explicar o salário, e armazene em uma variável;

71. Use a função train_test_split do sklearn para separar o dataset em dados de treino e teste, defina o test_size = 0.3 e random_state = 7;

72. Verifique o shape dos vetores de treino e teste criados;

73. Crie um modelo de regressão linear e ajuste aos dados de treino, use: from sklearn.linear_model import LinearRegression;

74. Calcule o coeficiente de determinação do modelo com a função score(), passando os dados de teste;

75. Gere um gráfico mostrando o grau de ajustamento da reta aos dados de teste;

76. Estime o modelo utilizando o método OLS, para tanto use a biblioteca statsmodels; mostre o coeficiente de determinação do modelo;

77. A partir do modelo OLS, gere um gráfico mostrando o grau de ajustamento da reta aos dados de teste.

Recursos para esta aula

pd.read_csv('../Dados/Salary_Data.csv')

In [40]:
a = np.ones(shape= 10)
b = np.ones(shape= (4,4))
c = np.ones(shape= (2,3), dtype= int)

print(a)
print()
print(b)
print()
print(c)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1 1 1]
 [1 1 1]]
