In [2]:
import numpy as np

# Exercício 1

**Inspecionando um Array NumPy**

Um objeto numpy possui atributos e métodos, herdados da classe (numpy.ndarray). Crie um array  e inspecione os seguintes atributos:

* shape: uma tupla que contém o número de elementos (tamanho) em cada dimensão do array;

* size: número total de elementos do array;

* ndim: número de dimensões (eixos);

* nbytes: número de bytes utilizado no armazenamento dos dados;

* dtype: data type dos elementos do array.



Exemplo de implementação:

```
import numpy as np
array = np.array([1, 2, 3, 4])
print('Shape: ', array.shape)
```



In [7]:
array = np.array([10, 5, 3, 200])
print(array.shape)
print(array.size)
print(array.ndim)
print(array.nbytes)
print(array.dtype)
print(type(array))

(4,)
4
1
32
int64
<class 'numpy.ndarray'>


# Exercício 2

Com base no exercício anterior crie uma função que receba um array e mostre na tela seus atributos. Verifique se o argumento inserido é de fato um objeto numpy. Use também a função built-in type() para verificar a classe do objeto.

Retorno esperado:

```
inspecionar_array(np.array([1,2,3]))
 
Shape : (3,)
Size:  3
Ndim:  1
Nbytes:  24
Dtype:  int64
Type:  <class 'numpy.ndarray'>
array([1, 2, 3, 4])


inspecionar_array([1,2,3])
 
'O objeto inserido não é um array NumPy.'
```

In [18]:
def inspecionar_array(array):
   if isinstance(array, np.ndarray):
    print(f'Shape: {array.shape}')
    print(f'Size: {array.size}')
    print(f'Ndim: {array.ndim}')
    print(f'Nbytes: {array.nbytes}')
    print(f'Dtype: {array.dtype}')
    print(f'Type: {type(array)}')
    print(array)
   else:
      return 'O objeto inserido não é um array NumPy.'

inspecionar_array(np.array([1,2,3,4]))
inspecionar_array([1,2,3])



Shape: (4,)
Size: 4
Ndim: 1
Nbytes: 32
Dtype: int64
Type: <class 'numpy.ndarray'>
[1 2 3 4]


'O objeto inserido não é um array NumPy.'

# Exercício 3

Use a função np.array() para criar os arrays unidimensionais listados abaixo:

a) Use uma lista como argumento e obtenha:
```
array([-1,  4,  7,  9])
```

b) Use a função range() e obtenha:
```    
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
```

c)Use uma tupla como argumento e obtenha:
```    
array([10, 11, 12, 13, 14])
```

d) Use a função range() e obtenha:
```    
array([1990, 1995, 2000, 2005, 2010, 2015, 2020])
```

e) Use a função range() e obtenha:
```
array([2020, 2010, 2000, 1990, 1980, 1970, 1960, 1950, 1940, 1930, 1920,
       1910, 1900])
```

f) Obtenha:
```
array(100)
```

In [39]:
a = np.array([-1, 4, 7, 9])
b = np.array(range(1,11))
tupla = (10,11,12,13,14)
c = np.array(tupla)
d = np.array(range(1990,2021,5))
e = np.array(range(2020,1899,-10))
f = np.array(100)

print(a)
print()
print(b)
print()
print(c)
print()
print(d)
print()
print(e)
print()
print(f)

[-1  4  7  9]

[ 1  2  3  4  5  6  7  8  9 10]

[10 11 12 13 14]

[1990 1995 2000 2005 2010 2015 2020]

[2020 2010 2000 1990 1980 1970 1960 1950 1940 1930 1920 1910 1900]

100


# Exercício 4

A função np.ones() permite criar um array preenchido com o número 1 em todas as suas entradas. Podemos especificar como argumentos o shape e o tipo de dado dtype do array. Use esta função para criar os arrays a seguir:

a)
```
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
```

b)
```
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
```       

c)
```
array([[1, 1],
       [1, 1],
       [1, 1]])
```

In [40]:
a = np.ones(shape= 10)
b = np.ones(shape= (4,4))
c = np.ones(shape= (2,3), dtype= int)

print(a)
print()
print(b)
print()
print(c)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1 1 1]
 [1 1 1]]


# Exercício 5

A função np.zeros() permite criar um array preenchido com o número 0 em todas as suas entradas. Podemos especificar como argumentos o shape e o tipo de dado dtype do array (default é o float). Use esta função para criar os arrays a seguir:

a)
```
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

b)
```
array([[0., 0.],
       [0., 0.]])  
```       

c)
```
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])
```

In [43]:
a = np.zeros(shape= 10)
b = np.zeros(shape= (2,2))
c = np.zeros(shape= (4,6))

print(a)
print()
print(b)
print()
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0.]
 [0. 0.]]

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# Exercício 6

Crie os arrays a seguir:

a)
```
array([[10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45]])
```

b)
```
array([-50, -45, -40, -35, -30, -25, -20, -15, -10,  -5])
```

c)
```
array([[ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
       [130, 132, 134, 136, 138, 140, 142, 144, 146, 148]])
```       

Dica: use np.arange() ou np.array(range()).

In [57]:
a = np.arange(start= 10, stop= 50, step= 5).reshape((-1, 1))
b = np.arange(start= -50, stop= -4, step= 5)
c = np.arange(start= 50, stop= 150, step= 2).reshape((-1,10))

print(a)
print()
print(b)
print()
print(c)

[[10]
 [15]
 [20]
 [25]
 [30]
 [35]
 [40]
 [45]]

[-50 -45 -40 -35 -30 -25 -20 -15 -10  -5]

[[ 50  52  54  56  58  60  62  64  66  68]
 [ 70  72  74  76  78  80  82  84  86  88]
 [ 90  92  94  96  98 100 102 104 106 108]
 [110 112 114 116 118 120 122 124 126 128]
 [130 132 134 136 138 140 142 144 146 148]]


# Exercício 7

Utilize a função np.full(shape, fill_value, dtype) para criar os arrays a seguir. Esta função permite criar um array com um shape e dtype definidos pelo usuário, preenchido com um determinado valor.

a)
```
array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])
```

b)
```
array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])
```

c)
```
array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])
```

d)
```
array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])
```

Dica: outra possibilidade seria obter os arrays com uma operação diferente, a partir da multiplicação de uma matriz preenchida com número 1 por um determinado valor.

In [64]:
a = np.full(shape= 10, fill_value= 5, dtype= float)
b = np.full(shape= (4,4), fill_value= -5, dtype= float)
c = np.full(shape= (3,3), fill_value= 3, dtype= int)
d = np.full(shape= (10,10), fill_value= 50)

print(a)
print()
print(b)
print()
print(c)
print()
print(d)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

[[-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]]

[[3 3 3]
 [3 3 3]
 [3 3 3]]

[[50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]]


# Exercício 8

Defina o array K e verifique se há dados ausentes (missing data). Use a função np.isnan().

```
array([[ nan,   1.,  10.,   0.],
       [ nan,  nan,  nan,  nan],
       [100.,  50.,  nan, -25.],
       [ 30.,  nan,  nan, 130.]])
```

In [71]:
K = np.array([[ np.NaN,   1.,  10.,   0.],
       [ np.NaN,  np.NaN,  np.NaN,  np.NaN],
       [100.,  50.,  np.NaN, -25.],
       [ 30.,  np.NaN,  np.NaN, 130.]])

np.isnan(K)

print(f'Há {np.isnan(k).sum()} dados ausentes em K')

Há 8 dados ausentes em K


# Exercício 9

A função np.linspace() retorna um array com números contendo espaçamento uniforme em um intervalo definido. Crie um array com números dentro do intervalo [1,21] em 5 partes.

Retorno esperado:
```
array([ 1.,  6., 11., 16., 21.])
```

In [74]:
np.linspace(start=1, stop=21, num= 5)

array([ 1.,  6., 11., 16., 21.])

# Exercício 10

A função np.logspace() retorna números com espaçamento uniforme em uma escala logarítmica. Crie um array com números dentro do intervalo [1, 51] em 10 partes com a função np.logspace().

Retorno esperado:
```
array([[1.00000000e+01],
       [3.59381366e+06],
       [1.29154967e+12],
       [4.64158883e+17],
       [1.66810054e+23],
       [5.99484250e+28],
       [2.15443469e+34],
       [7.74263683e+39],
       [2.78255940e+45],
       [1.00000000e+51]])
```


In [79]:
np.logspace(start=1, stop=51, num=10).reshape(-1,1)

array([[1.00000000e+01],
       [3.59381366e+06],
       [1.29154967e+12],
       [4.64158883e+17],
       [1.66810054e+23],
       [5.99484250e+28],
       [2.15443469e+34],
       [7.74263683e+39],
       [2.78255940e+45],
       [1.00000000e+51]])

# Exercício 11

Use a função np.diag() para construir o array a seguir:

```
array([[ 5,  0,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0,  0],
       [ 0,  0, 15,  0,  0,  0],
       [ 0,  0,  0, 20,  0,  0],
       [ 0,  0,  0,  0, 25,  0],
       [ 0,  0,  0,  0,  0, 30]])
```

In [86]:
np.diag(range(5,31,5))

array([[ 5,  0,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0,  0],
       [ 0,  0, 15,  0,  0,  0],
       [ 0,  0,  0, 20,  0,  0],
       [ 0,  0,  0,  0, 25,  0],
       [ 0,  0,  0,  0,  0, 30]])

# Exercício 12

Use a função np.eye() (ou ainda np.identity()) para obter o array seguir.


```
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])
```

Dica: essa matriz é definida como matriz identidade, neste caso de ordem 10, e assume grande relevância em diversos cálculos computacionais, como veremos mais adiante.



In [90]:
np.eye(N=10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Exercício 14

Obtenha a soma dos elementos de cada array a seguir. Use a função np.sum(). Implemente uma solução com loop for, para tanto armazene os vetores em uma lista.

```
import numpy as np
array1 = np.arange(1,11)
array2 = np.linspace(1,50,10)
array3 = np.array(range(51))
array4 = np.logspace(1,10,5)
array5 = np.diag(range(5,31,5))
```
Retorno esperado:

```
Soma dos elementos do array 1:  55
Soma dos elementos do array 2:  255.0
Soma dos elementos do array 3:  1275
Soma dos elementos do array 4:  10056552148.564463
Soma dos elementos do array 5:  105
```

In [111]:
array1 = np.arange(1,11)
array2 = np.linspace(1,50,10)
array3 = np.array(range(51))
array4 = np.logspace(1,10,5)
array5 = np.diag(range(5,31,5))

lista_array = [array1,array2,array3,array4,array5]

i = 1
for array in lista_array:
    print(f'Soma dos elementos do array {i}: {np.sum(array)}')
    i = i + 1


Soma dos elementos do array 1: 55
Soma dos elementos do array 2: 255.0
Soma dos elementos do array 3: 1275
Soma dos elementos do array 4: 10056552148.564463
Soma dos elementos do array 5: 105


# Exercício 15

A partir da matriz definida abaixo obtenha: a) soma total dos elementos; b) soma das linhas ; c) soma das colunas.

```
import numpy as np
matriz = np.array(np.random.randint(1,100,15)).reshape(5,3)
```

In [116]:
matriz = np.array(np.random.randint(1,100,15)).reshape(5,3)

a = np.sum(matriz)
b = np.sum(matriz, axis=0)
c = np.sum(matriz, axis=1)

print(a)
print()
print(b)
print()
print(c)

672

[221 259 192]

[153 140  77 226  76]


# Exercício 16

Obtenha o valor máximo e o valor mínimo de cada array abaixo. Implemente uma solução com loop for.

```
import numpy as np
array1 = np.array([-1, 10, 3, 4, 7, 27])
array2 = np.random.randint(-100,300,30)
array3 = np.random.randn(10)
array4 = np.array(range(50,10,-2))
```

Dica: para obter o valor máximo e mínimo de um array podemos usar array.max() e array.min() ( ou ainda max(array) e min(array)).

In [124]:
array1 = np.array([-1, 10, 3, 4, 7, 27])
array2 = np.random.randint(-100,300,30)
array3 = np.random.randn(10)
array4 = np.array(range(50,10,-2))

array = [array1, array2, array3, array4]

for index,array in enumerate(array):
    print(f'Array{index}. Valor máximo: {np.max(array)}. Valor mínimo: {np.min(array)}.\n') 

Array0. Valor máximo: 27. Valor mínimo: -1.

Array1. Valor máximo: 291. Valor mínimo: -90.

Array2. Valor máximo: 1.8187054051136464. Valor mínimo: -1.3471127933677782.

Array3. Valor máximo: 50. Valor mínimo: 12.



# Exercício 17

Crie uma função que receba uma matriz como entrada e calcule:

    a) Valor máximo da matriz;

    b) Valor máximo por coluna;

    c) Valor máximo por linha;

    d) Valor mínimo da matriz;

    e) Valor mínimo por coluna;

    f) Valor mínimo por linha.



Exemplo de retorno para a matriz definida abaixo:

Input:
```
matriz = np.random.randint(-1000,1000,50).reshape(10,5)
info_matriz(matriz)
```
Output:
```
Valor máximo da matriz:  987
Valor máximo por coluna:  [959 987 597 748 719]
Valor máximo por linha:  [ 987  312  982  204  719  689  101  793 -460  959]
Valor mínimo da matriz:  -969
Valor mínimo por coluna:  [-878 -966 -969 -884 -881]
Valor mínimo por linha:  [  30 -878 -335 -863  -40 -289 -660 -239 -969 -966]
```

In [126]:
def info_matriz(matriz):
    print(f'Valor máximo da matriz: {np.max(matriz)}')
    print(f'Valor máximo por coluna: {np.max(matriz, axis=1)}')
    print(f'Valor máximo por linha: {np.max(matriz, axis=0)}')
    print(f'Valor mínimo da matriz: {np.min(matriz)}')
    print(f'Valor mínimo por coluna: {np.min(matriz, axis=1)}')
    print(f'Valor mínimo por linha: {np.min(matriz, axis=0)}')

matriz = np.random.randint(-1000,1000,50).reshape(10,5)
info_matriz(matriz)

Valor máximo da matriz: 988
Valor máximo por coluna: [ 712 -136  392  970  743  988  960  850  817  491]
Valor máximo por linha: [786 970 807 988 960]
Valor mínimo da matriz: -975
Valor mínimo por coluna: [-637 -753 -626 -658 -858 -772 -834 -975   14 -921]
Valor mínimo por linha: [-658 -921 -637 -858 -975]


# Exercício 18

Com base no array definido abaixo obtenha sua média, mediana, variância e desvio padrão.

```
import numpy as np
arr = np.random.normal(40,0.5,size = (300))
```

Dica:

Média: np.mean();

Mediana: np.median();

Desvio padrão: np.std();

Variância: np.var().

In [128]:
arr = np.random.normal(40,0.5,size = (300))

print(f'Média: {np.mean(arr)}\n')

print(f'Mediana: {np.median(arr)}\n')

print(f'Desvio padrão: {np.std(arr)}\n')

print(f'Variância: {np.var(arr)}')

Média: 40.03215278872069

Mediana: 40.02200045971733

Desvio padrão: 0.46974165512707733

Variância: 0.22065722256152606


# Exercício 19

Com base nos arrays definidos a seguir obtenha a matriz de covariância e a matriz de correlação.

```
import numpy as np
x = np.random.rand(100)
y = np.random.uniform(size=100)
```

Dica: use np.corrcoef() e np.cov().

In [130]:
x = np.random.rand(100)
y = np.random.uniform(size=100)

print('Para x:')
print(f'Matriz de covariância: {np.corrcoef(x)}')
print(f'Matriz de correlação {np.cov(x)}\n')
print('Para y:')
print(f'Matriz de covariância: {np.corrcoef(y)}')
print(f'Matriz de correlação {np.cov(y)}')

Para x:
Matriz de covariância: 1.0
Matriz de correlação 0.08779529353604297

Para y:
Matriz de covariância: 1.0
Matriz de correlação 0.07696748417977765


# Exercício 20

Obtenha o índice do valor máximo do array A.

```
A = np.array([[11, 15, 33, 105],
              [1, 140, 45, 90],
              [67, 230, 78, 99]])
```

Dica: use np.argmax() ou array.argmax().

In [131]:
A = np.array([[11, 15, 33, 105],
              [1, 140, 45, 90],
              [67, 230, 78, 99]])

np.argmax(A)

9

# Exercício 21

Obtenha o índice do valor mínimo do array B.

```
B = np.array([
    [73, 22, 20, 62,  3],
    [68, 84, 27, 59, 93],
    [48, 52,  4, 55, 50],
    [42, 23, 63, 67,  4],
    [44, 30, 41, 31, 29]])
```

Dica: use np.argmin() ou array.argmin().

In [132]:
B = np.array([
    [73, 22, 20, 62,  3],
    [68, 84, 27, 59, 93],
    [48, 52,  4, 55, 50],
    [42, 23, 63, 67,  4],
    [44, 30, 41, 31, 29]])

np.argmin(B)

4

# Exercício 22

Escreva uma função que receba um array NumPy e mostre na tela um conjunto de  estatísticas descritivas deste objeto.

Resultado esperado:

Input
```
array = np.array([-57, 101, 270, 130, 144])
info_array(array)
```

Output:
```
Valor máximo: 270
Valor mínimo: -57
Média: 117.6
Mediana: 130.0
Variância: 10967.439999999999
Desvio padrão: 104.72554607162475
```

In [133]:
def info_array(array):
    print(f'Valor máximo: {np.max(array)}')
    print(f'Valor mínimo: {np.min(array)}')
    print(f'Média: {np.mean(array)}')
    print(f'Mediana: {np.median(array)}')
    print(f'Variância: {np.var(array)}')
    print(f'Desvio padrão: {np.std(array)}')

array = np.array([-57, 101, 270, 130, 144])
info_array(array)

Valor máximo: 270
Valor mínimo: -57
Média: 117.6
Mediana: 130.0
Variância: 10967.439999999999
Desvio padrão: 104.72554607162475


# Exercício 23

Use a função np.unique() para obter um array com os elementos únicos do array abaixo. Para tanto, armazene o novo array em uma variável.

```
A = np.array([
    [1, 3, 3, 4, 5],
    [4, 7, 11, 3, 5],
    [1, 11, 4, 4, 11]])
```

In [134]:
A = np.array([
    [1, 3, 3, 4, 5],
    [4, 7, 11, 3, 5],
    [1, 11, 4, 4, 11]])

X = np.unique(A)
print(X)

[ 1  3  4  5  7 11]


# Exercício 24

Indexação de arrays 1-D

Considerando os arrays abaixo:
```
import numpy as np
array1 = np.array([10, 20, 30, 40])
array2 = np.array([100, 30, 5, 1, 40, 100, 20, 130, 155,170])
```

Obtenha:

a) o primeiro, o terceiro e o último elemento de cada array;

b) inverta o array;

c) pegue o número 20 em ambos os arrays e armazene a soma em uma variável.

   

In [142]:
array1 = np.array([10, 20, 30, 40])
array2 = np.array([100, 30, 5, 1, 40, 100, 20, 130, 155,170])

array_list = [array1, array2]

for index, array in enumerate(array_list, start=1):
    print(f'array{index}\n'
    f'Primeiro elemento: {array[0]}.\n'
    f'Terceiro elemento: {array[0]}.\n'
    f'Último elemento: {array[-1]}\n'
    f'Array invertido: {array[::-1]}\n')

soma = array1[1] + array2[6]
print(soma)

array1
Primeiro elemento: 10.
Terceiro elemento: 10.
Último elemento: 40
Array invertido: [40 30 20 10]

array2
Primeiro elemento: 100.
Terceiro elemento: 100.
Último elemento: 170
Array invertido: [170 155 130  20 100  40   1   5  30 100]

40


# Exercício 25

Indexação de arrays 2-D

Acesse os números 9 e 90 do array abaixo.

```
import numpy as np
ar = np.array([[-1, 33, 44, 9, 1],[11, 1, 0, 90, 44]])
```

In [143]:
ar = np.array([[-1, 33, 44, 9, 1],[11, 1, 0, 90, 44]])
print(ar[0][3])
print(ar[1][3])

9
90


# Exercício 26

Indexação de arrays 3-D

Acesse os números 5, 9, 3 e 21 do array abaixo.

```
import numpy as np
ar = np.array([
    [[1, 1, 5, 1],
     [1, 1, 1, 9]],
    [[1, 3, 1, 1],
     [1, 1, 21, 1]]
              ])
```

In [147]:
ar = np.array([
    [[1, 1, 5, 1],
     [1, 1, 1, 9]],
    [[1, 3, 1, 1],
     [1, 1, 21, 1]]
              ])

print(ar[0][0][2])
print(ar[0][1][3])
print(ar[1][0][1])
print(ar[1][1][2])

5
9
3
21


# Exercício 27

Slicing 1-D

Com base no array abaixo obtenha o slice do índice 2 até o índice 6.
```
import numpy as np
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
```

Dica: Em Python, slicing significa que podemos selecionar elementos entre índices especificados. Sintaxe: [start:end:pass].

Se não especificarmos o start o valor default será 0. Se não definirmos o step, será considerado o valor 1.

In [148]:
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
ar[2:7]

array([3, 4, 5, 6, 7])