In [2]:
import numpy as np

# Exercício 1

Gere uma distribuição normal aleatória de ordem 4 x 5. Armazene o resultado em uma variável.


In [7]:
array = np.array([10, 5, 3, 200])
print(array.shape)
print(array.size)
print(array.ndim)
print(array.nbytes)
print(array.dtype)
print(type(array))

(4,)
4
1
32
int64
<class 'numpy.ndarray'>


# Exercício 2

Gere uma distribuição normal aleatória com de ordem 20 x 5, com média 10 e desvio padrão 3. Armazene o resultado em uma variável. Em seguida crie um DataFrame a partir dos dados criados.

In [18]:
def inspecionar_array(array):
   if isinstance(array, np.ndarray):
    print(f'Shape: {array.shape}')
    print(f'Size: {array.size}')
    print(f'Ndim: {array.ndim}')
    print(f'Nbytes: {array.nbytes}')
    print(f'Dtype: {array.dtype}')
    print(f'Type: {type(array)}')
    print(array)
   else:
      return 'O objeto inserido não é um array NumPy.'

inspecionar_array(np.array([1,2,3,4]))
inspecionar_array([1,2,3])



Shape: (4,)
Size: 4
Ndim: 1
Nbytes: 32
Dtype: int64
Type: <class 'numpy.ndarray'>
[1 2 3 4]


'O objeto inserido não é um array NumPy.'

# Exercício 3

Gere uma distribuição normal padrão e utilize o módulo Seaborn para construir uma visualização dos dados. A amostra deve conter 3000 números. Use a função distplot() do módulo Seaborn e importe também

In [39]:
a = np.array([-1, 4, 7, 9])
b = np.array(range(1,11))
tupla = (10,11,12,13,14)
c = np.array(tupla)
d = np.array(range(1990,2021,5))
e = np.array(range(2020,1899,-10))
f = np.array(100)

print(a)
print()
print(b)
print()
print(c)
print()
print(d)
print()
print(e)
print()
print(f)

[-1  4  7  9]

[ 1  2  3  4  5  6  7  8  9 10]

[10 11 12 13 14]

[1990 1995 2000 2005 2010 2015 2020]

[2020 2010 2000 1990 1980 1970 1960 1950 1940 1930 1920 1910 1900]

100


# Exercício 4

A distribuição binomial é uma distribuição discreta de probabilidade e descreve resultados binários, como sucesso e fracasso ou cara e coroa, por exemplo. Podemos criar dados aleatórios para esta distribuição com a função np.random.binomial().Sendo:

* n: número de tentativas;

* p: probabilidade de ocorrência de cada tentativa;

* size: tamanho do vetor retornado (shape).

Com base nestas informações:

* Gere números aleatórios seguindo uma distribuição binomial, com 6 tentativas, em que a probabilidade de ocorrência de cada tentativa é 0.5, e tamanho 100. Armazene os dados em uma variável, 'data1'.

* Gere números aleatórios seguindo uma distribuição binomial, com 2 tentativas, em que a probabilidade de ocorrência de cada tentativa é 0.8, e tamanho 1000. Armazene os dados em uma variável, 'data2'.

In [40]:
a = np.ones(shape= 10)
b = np.ones(shape= (4,4))
c = np.ones(shape= (2,3), dtype= int)

print(a)
print()
print(b)
print()
print(c)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1 1 1]
 [1 1 1]]


# Exercício 5

Use o módulo Seaborn para visualizar a distribuição de números aleatórios oriunda de uma distribuição binomial, com 6 tentativas, probabilidade 0.5 e tamanho 3000.

In [43]:
a = np.zeros(shape= 10)
b = np.zeros(shape= (2,2))
c = np.zeros(shape= (4,6))

print(a)
print()
print(b)
print()
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0.]
 [0. 0.]]

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# Exercício 6

A distribuição uniforme é uma distribuição contínua de probabilidade, com importantes aplicações em estatística. Gere uma amostra da distribuição uniforme de shape 3 x 3.
Dica: use np.random.uniform().

In [57]:
a = np.arange(start= 10, stop= 50, step= 5).reshape((-1, 1))
b = np.arange(start= -50, stop= -4, step= 5)
c = np.arange(start= 50, stop= 150, step= 2).reshape((-1,10))

print(a)
print()
print(b)
print()
print(c)

[[10]
 [15]
 [20]
 [25]
 [30]
 [35]
 [40]
 [45]]

[-50 -45 -40 -35 -30 -25 -20 -15 -10  -5]

[[ 50  52  54  56  58  60  62  64  66  68]
 [ 70  72  74  76  78  80  82  84  86  88]
 [ 90  92  94  96  98 100 102 104 106 108]
 [110 112 114 116 118 120 122 124 126 128]
 [130 132 134 136 138 140 142 144 146 148]]


# Exercício 7

Use o módulo Seaborn para visualizar a distribuição de números aleatórios oriunda de uma distribuição uniforme, de tamanho 1000.

In [64]:
a = np.full(shape= 10, fill_value= 5, dtype= float)
b = np.full(shape= (4,4), fill_value= -5, dtype= float)
c = np.full(shape= (3,3), fill_value= 3, dtype= int)
d = np.full(shape= (10,10), fill_value= 50)

print(a)
print()
print(b)
print()
print(c)
print()
print(d)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

[[-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]]

[[3 3 3]
 [3 3 3]
 [3 3 3]]

[[50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]]


# Exercício 8

Gere um array com números aleatórios entre -1000 e 3000, de shape (30, 5).
Dica: np.random.randint().

In [71]:
K = np.array([[ np.NaN,   1.,  10.,   0.],
       [ np.NaN,  np.NaN,  np.NaN,  np.NaN],
       [100.,  50.,  np.NaN, -25.],
       [ 30.,  np.NaN,  np.NaN, 130.]])

np.isnan(K)

print(f'Há {np.isnan(k).sum()} dados ausentes em K')

Há 8 dados ausentes em K


# Exercício 9

Gere um array de shape 30 x 5 com números entre 0 e 4, inclusive.

In [74]:
np.linspace(start=1, stop=21, num= 5)

array([ 1.,  6., 11., 16., 21.])

# Exercício 10

Gere um array de números inteiros com limites superiores diferentes (100, 300, 50, 10000), mas com valor mínimo 10.


In [79]:
np.logspace(start=1, stop=51, num=10).reshape(-1,1)

array([[1.00000000e+01],
       [3.59381366e+06],
       [1.29154967e+12],
       [4.64158883e+17],
       [1.66810054e+23],
       [5.99484250e+28],
       [2.15443469e+34],
       [7.74263683e+39],
       [2.78255940e+45],
       [1.00000000e+51]])

# Exercício 11

Utilize a função np.random.rand() para gerar um array 10 x 5. Lembre que esta função gera por padrão números aleatórios de acordo com uma distribuição uniforme no intervalo [0,1). Em seguida mostre na tela a média, desvio padrão e mediana do array gerado.

In [86]:
np.diag(range(5,31,5))

array([[ 5,  0,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0,  0],
       [ 0,  0, 15,  0,  0,  0],
       [ 0,  0,  0, 20,  0,  0],
       [ 0,  0,  0,  0, 25,  0],
       [ 0,  0,  0,  0,  0, 30]])

# Exercício 12

Use a função np.random.randn() para gerar um array com números aleatórios de uma distribuição normal padrão, de shape 30 x 3. Seguidamente, crie um DataFrame com os dados criados e gere uma visualização da distribuição de probabilidade de cada coluna com o módulo Seaborn.



In [90]:
np.eye(N=10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Exercício 13

Gere um array com 800 números aleatórios de acordo com uma distribuição exponencial padrão. Use a função np.random.standard_exponential().

In [111]:
array1 = np.arange(1,11)
array2 = np.linspace(1,50,10)
array3 = np.array(range(51))
array4 = np.logspace(1,10,5)
array5 = np.diag(range(5,31,5))

lista_array = [array1,array2,array3,array4,array5]

i = 1
for array in lista_array:
    print(f'Soma dos elementos do array {i}: {np.sum(array)}')
    i = i + 1


Soma dos elementos do array 1: 55
Soma dos elementos do array 2: 255.0
Soma dos elementos do array 3: 1275
Soma dos elementos do array 4: 10056552148.564463
Soma dos elementos do array 5: 105


# Exercício 14

A distribuição de Poisson é uma distribuição discreta de probabilidade. Esta distribuição descreve quantas vezes um determinado evento pode ocorrer em um tempo especificado. A biblioteca NumPy permite gerar números aleatórios desta distribuição com a função np.random.poisson(). Gere uma distribuição aleatória de shape 50 x 3, com número conhecido de ocorrências igual a 5.

In [116]:
matriz = np.array(np.random.randint(1,100,15)).reshape(5,3)

a = np.sum(matriz)
b = np.sum(matriz, axis=0)
c = np.sum(matriz, axis=1)

print(a)
print()
print(b)
print()
print(c)

672

[221 259 192]

[153 140  77 226  76]


# Exercício 15

Gere uma distribuição aleatória de Poisson com 10.000 amostras, em que o número conhecido de ocorrências é igual 3. Armazene os dados em um objeto Pandas Series.

In [124]:
array1 = np.array([-1, 10, 3, 4, 7, 27])
array2 = np.random.randint(-100,300,30)
array3 = np.random.randn(10)
array4 = np.array(range(50,10,-2))

array = [array1, array2, array3, array4]

for index,array in enumerate(array):
    print(f'Array{index}. Valor máximo: {np.max(array)}. Valor mínimo: {np.min(array)}.\n') 

Array0. Valor máximo: 27. Valor mínimo: -1.

Array1. Valor máximo: 291. Valor mínimo: -90.

Array2. Valor máximo: 1.8187054051136464. Valor mínimo: -1.3471127933677782.

Array3. Valor máximo: 50. Valor mínimo: 12.



# Exercício 16

A função np.random.choice() gera uma amostra aleatória de um array unidimensional. Gere uma amostra aleatória de tamanho 10, a partir das letras 'a', 'b', 'c', 'd'.

In [126]:
def info_matriz(matriz):
    print(f'Valor máximo da matriz: {np.max(matriz)}')
    print(f'Valor máximo por coluna: {np.max(matriz, axis=1)}')
    print(f'Valor máximo por linha: {np.max(matriz, axis=0)}')
    print(f'Valor mínimo da matriz: {np.min(matriz)}')
    print(f'Valor mínimo por coluna: {np.min(matriz, axis=1)}')
    print(f'Valor mínimo por linha: {np.min(matriz, axis=0)}')

matriz = np.random.randint(-1000,1000,50).reshape(10,5)
info_matriz(matriz)

Valor máximo da matriz: 988
Valor máximo por coluna: [ 712 -136  392  970  743  988  960  850  817  491]
Valor máximo por linha: [786 970 807 988 960]
Valor mínimo da matriz: -975
Valor mínimo por coluna: [-637 -753 -626 -658 -858 -772 -834 -975   14 -921]
Valor mínimo por linha: [-658 -921 -637 -858 -975]


# Exercício 17

Gere um DataFrame com 7 colunas e 100 linhas, com as seguintes características:

* a coluna 'A' segue uma distribuição normal padrão;

* a coluna 'B' segue uma distribuição uniforme;

* a coluna 'C' segue uma distribuição binomial, com 6 tentativas e probabilidade de sucesso 0.6;

* a coluna 'D' segue uma distribuição exponencial padrão;

* a coluna 'E' segue uma distribuição de Poisson com número conhecido de ocorrências igual a 10;

* a coluna 'F' segue uma distribuição normal de média 100 e desvio padrão 15;

* a coluna 'G' possui números aleatórios inteiros entre 50 e 3000.

In [128]:
arr = np.random.normal(40,0.5,size = (300))

print(f'Média: {np.mean(arr)}\n')

print(f'Mediana: {np.median(arr)}\n')

print(f'Desvio padrão: {np.std(arr)}\n')

print(f'Variância: {np.var(arr)}')

Média: 40.03215278872069

Mediana: 40.02200045971733

Desvio padrão: 0.46974165512707733

Variância: 0.22065722256152606


# Exercício 18

* Gere uma amostra da distribuição Qui-Quadrado com 3 graus de liberdade e shape 5 x 5;

* Gere uma amostra da distribuição Qui-Quadrado com 2 graus de liberdade e tamanho 2.000 e plot um gráfico para visualizar a distribuição de probabilidade gerada;

* Gere uma amostra de uma distribuição Exponencial com scale 5 e shape 2 x 2.

In [130]:
x = np.random.rand(100)
y = np.random.uniform(size=100)

print('Para x:')
print(f'Matriz de covariância: {np.corrcoef(x)}')
print(f'Matriz de correlação {np.cov(x)}\n')
print('Para y:')
print(f'Matriz de covariância: {np.corrcoef(y)}')
print(f'Matriz de correlação {np.cov(y)}')

Para x:
Matriz de covariância: 1.0
Matriz de correlação 0.08779529353604297

Para y:
Matriz de covariância: 1.0
Matriz de correlação 0.07696748417977765


# Exercício 19

A distribuição logística é amplamente utilizada em Machine Learning e Redes Neurais. Gere um vetor com números aleatórios de uma amostra de tamanho 100, gerado por meio de uma distribuição logística com média 5 e desvio padrão 0.9.

In [131]:
A = np.array([[11, 15, 33, 105],
              [1, 140, 45, 90],
              [67, 230, 78, 99]])

np.argmax(A)

9

# Exercício 20

Construa dois vetores de tamanho 100, com média 1 e desvio padrão 0.5, sendo que o primeiro segue uma distribuição normal, ao passo que o segundo vetor segue uma distribuição logística. Em seguida construa um DataFrame com os números aleatórios criados e gere um gráfico único que mostre ambas as distribuições aleatórias geradas.

In [132]:
B = np.array([
    [73, 22, 20, 62,  3],
    [68, 84, 27, 59, 93],
    [48, 52,  4, 55, 50],
    [42, 23, 63, 67,  4],
    [44, 30, 41, 31, 29]])

np.argmin(B)

4